### ISSUE TITLE
Mod doesn't work well with other mods.

### ISSUE THREAD

**Issue by Claycorp** [DoubleDoorDevelopment/InventoryLock#2]
http://pastebin.com/NZ7XzDdV

**Comment by dries007** [comment]
wut?

**Comment by Claycorp** [comment]
I have no clue. Your black magic must have broke someone else's stuff or something.

**Comment by Claycorp** [comment]
Here is another crashlog that might help with some of it.
http://pastebin.com/8yPxKrtH
