### ISSUE TITLE
Locked inventories do not let people in.

### ISSUE THREAD

**Issue by Claycorp** [DoubleDoorDevelopment/InventoryLock#3]
Lock block. Nobody can open. Not even OPs

**Comment by dries007** [comment]
wat?

**Comment by Claycorp** [comment]
Exactly as it says. "vanilla" server and you lock something nobody can open it. Not one. and OP bypass doesn't work.

There was three of us testing and even if i added a new person nobody could open it. we tested hoppers chests and furnaces.
