### ISSUE TITLE
Wands are named oddly. Unsure if this was intentional or not

### ISSUE THREAD

**Issue by Claycorp** [DoubleDoorDevelopment/InventoryLock#8]
Old: http://i.imgur.com/KmGVgqA.png
New: http://i.imgur.com/1OXyRBp.png

**Comment by dries007** [comment]
It's intended, as an indicator of proper working order. Perhaps it would be better as 2nd or 3rd line. (Its a client side mod thing, so it won't appear on vanilla.)
